config/routes.rb
Rails.application.routes.draw do

  resources :reports
  resources :slides
  resources :prices
  scope "(:city)", city: /nn/ do
    get '', to: 'pages#index' 
    # get 'career', to: 'pages#career' 
  end
  # resources :posts
  # get 'user/index'
  # # resources :pages
  # get 'testpath', to: 'pages#testpage'

  root 'pages#index'


  # scope '/admin' do
  #   resources :articles, :comments
  # end

  # resources :articles, path: '/admin/articles'
  # resources :comments, path: '/admin/comments'

  resources :articles


  # namespace :admin do
  #   resources :articles
  # end
  
  # resources :comments do
  #   get 'preview', to: 'test#tt'
  # end

  # resources :articles do
  #   resources :comments, only: [:index, :new, :create]
  # end
  # resources :comments, only: [:show, :edit, :update, :destroy]

  resources :articles do
    resources :comments
  end


  # scope shallow_path: "sekret" do
  #   resources :articles do
  #     resources :comments, shallow: true
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/slide.rb
class Slide < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    # render plain: params[:article].inspect
    # render plain: @article.inspect

    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      # render plain: params[:article].inspect
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text, :image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @post = Post.new

    @city = 'msk'

    if params[:city].presence
      @city = params[:city]
    end
  end
  def new
    @post = Post.new
  end
  def testpage
    # @post 
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  # GET /prices
  def index
    @prices = Price.all
  end

  # GET /prices/1
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
  end

  # POST /prices
  def create
    @price = Price.new(price_params)

    if @price.save
      redirect_to @price, notice: 'Price was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /prices/1
  def update
    if @price.update(price_params)
      redirect_to @price, notice: 'Price was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /prices/1
  def destroy
    @price.destroy
    redirect_to prices_url, notice: 'Price was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def price_params
      params.require(:price).permit(:title, :price, :pricenn)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  def index
    @reports = Report.all
  end

  # GET /reports/1
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  def create
    @report = Report.new(report_params)

    if @report.save
      redirect_to @report, notice: 'Report was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reports/1
  def update
    if @report.update(report_params)
      redirect_to @report, notice: 'Report was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /reports/1
  def destroy
    @report.destroy
    redirect_to reports_url, notice: 'Report was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def report_params
      params.require(:report).permit(:name, :desc)
    end
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  def create
    @slide = Slide.new(slide_params)

    if @slide.save
      redirect_to @slide, notice: 'Slide was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /slides/1
  def update
    if @slide.update(slide_params)
      redirect_to @slide, notice: 'Slide was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /slides/1
  def destroy
    @slide.destroy
    redirect_to slides_url, notice: 'Slide was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def slide_params
      params.require(:slide).permit(:name, :link, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/articles/_form.html.slim
= form_with model: @article, local:true do |form|
  - if @article.errors.any?
    #error_explanation
      h2
        = pluralize(@article.errors.count, "error")
        |&nbsp;prohibited this article from being saved:
      ul
        - @article.errors.full_messages.each do |msg| 
          li = msg
        end 

  p
    = form.label :title
    = form.text_field :title
 
  p
    = form.label :text
    = form.text_area :text
    / = debug @article.image
    - if @article.image.presence 
      / = debug @article.image.url
      = image_tag @article.image.preview.url
    = form.file_field :image
 
  p
   = form.submit
  p

app/views/articles/edit.html.slim
h1 Edit article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/index.html.slim
p = link_to 'New artcile', new_article_path
table
  - @articles.each do |article|
    tr 
      td = article.title
      td = article.text
      td = link_to 'Show', article_path(article)
      td = link_to 'Edit', edit_article_path(article)
      td = link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' }
  end

app/views/articles/new.html.slim
h1 articles

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
p
  strong Title:
  = @article.title
 
p
  strong Text:
  = @article.text

h2 Comments
=render @article.comments

h2 Add a comment:
= render 'comments/form'

= link_to 'Edit', edit_article_path(@article)
|&nbsp;
= link_to 'Back', articles_path

app/views/comments/_comment.html.slim
p
  strong Commenter:
  = comment.commenter
 
p
  strong Comment:
  = comment.body

p 
  = link_to 'Destroy comment', [comment.article, comment], method: :delete, data: {confirm: 'Are you sure?'}

app/views/comments/_form.html.slim
= form_with(model: [ @article, @article.comments.build ], local: true) do |form|
  p
    = form.label :commenter 
    = form.text_field :commenter
  p
    = form.label :body
    = form.text_area :body
  p
    = form.submit 

app/views/layouts/application.html.slim
doctype html
html
  head
    title First
    = tag('meta', { name: 'viewport', content: 'width=device-width, initial-scale=1.0' })

    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = yield
  .master
    | master
    | tester

app/views/pages/index.html.slim
h1 Header
= @city
= link_to 'My Blog', articles_path
.sss
  | sadasdas

app/views/prices/_form.html.slim
= simple_form_for(@price) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :price
    = f.input :pricenn

  .form-actions
    = f.button :submit

app/views/prices/edit.html.slim
h1 Editing price

== render 'form'

=> link_to 'Show', @price
'|
=< link_to 'Back', prices_path

app/views/prices/index.html.slim
h1 Listing prices

table
  thead
    tr
      th Title
      th Price
      th Pricenn
      th
      th
      th

  tbody
    - @prices.each do |price|
      tr
        td = price.title
        td = price.price
        td = price.pricenn
        td = link_to 'Show', price
        td = link_to 'Edit', edit_price_path(price)
        td = link_to 'Destroy', price, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Price', new_price_path

app/views/prices/new.html.slim
h1 New price

== render 'form'

= link_to 'Back', prices_path

app/views/prices/show.html.slim
p#notice = notice

p
  strong Title:
  = @price.title
p
  strong Price:
  = @price.price
p
  strong Pricenn:
  = @price.pricenn

=> link_to 'Edit', edit_price_path(@price)
'|
=< link_to 'Back', prices_path

app/views/reports/_form.html.slim
= simple_form_for(@report) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :desc

  .form-actions
    = f.button :submit

app/views/reports/edit.html.slim
h1 Editing report

== render 'form'

=> link_to 'Show', @report
'|
=< link_to 'Back', reports_path

app/views/reports/index.html.slim
h1 Listing reports

table
  thead
    tr
      th Name
      th Desc
      th
      th
      th

  tbody
    - @reports.each do |report|
      tr
        td = report.name
        td = report.desc
        td = link_to 'Show', report
        td = link_to 'Edit', edit_report_path(report)
        td = link_to 'Destroy', report, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Report', new_report_path

app/views/reports/new.html.slim
h1 New report

== render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.slim
p#notice = notice

p
  strong Name:
  = @report.name
p
  strong Desc:
  = @report.desc

=> link_to 'Edit', edit_report_path(@report)
'|
=< link_to 'Back', reports_path

app/views/slides/_form.html.slim
= simple_form_for(@slide) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :link
    = f.input :image

  .form-actions
    = f.button :submit

app/views/slides/edit.html.slim
h1 Editing slide

== render 'form'

=> link_to 'Show', @slide
'|
=< link_to 'Back', slides_path

app/views/slides/index.html.slim
h1 Listing slides

table
  thead
    tr
      th Name
      th Link
      th Image
      th
      th
      th

  tbody
    - @slides.each do |slide|
      tr
        td = slide.name
        td = slide.link
        td = slide.image
        td = link_to 'Show', slide
        td = link_to 'Edit', edit_slide_path(slide)
        td = link_to 'Destroy', slide, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Slide', new_slide_path

app/views/slides/new.html.slim
h1 New slide

== render 'form'

= link_to 'Back', slides_path

app/views/slides/show.html.slim
p#notice = notice

p
  strong Name:
  = @slide.name
p
  strong Link:
  = @slide.link
p
  strong Image:
  = @slide.image

=> link_to 'Edit', edit_slide_path(@slide)
'|
=< link_to 'Back', slides_path